User.create([
	{first_name: "Josh", last_name: "Miramant", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
	{first_name: "Dummy", last_name: "Account", profile_score: rand(100), company_id: rand(30), location: 94108},
])


Company.create([
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
	{name: "Good.Co", size: rand(100), industry: "tech", profile_score: rand(100)},
])


Follow.create([
	{user_id_one: 1, user_id_two: 2},
	{user_id_one: 1, user_id_two: 3},
	{user_id_one: 1, user_id_two: 4},
	{user_id_one: 1, user_id_two: 5},
	{user_id_one: 1, user_id_two: 6},	
	{user_id_one: 1, user_id_two: 7},
	{user_id_one: 1, user_id_two: 8},
	{user_id_one: 1, user_id_two: 9},
	{user_id_one: 1, user_id_two: 10},
	{user_id_one: 1, user_id_two: 11},
	{user_id_one: 1, user_id_two: 12},
	{user_id_one: 1, user_id_two: 13},
	{user_id_one: 1, user_id_two: 14},
	{user_id_one: 1, user_id_two: 15},
	{user_id_one: 1, user_id_two: 16},	
	{user_id_one: 1, user_id_two: 17},
	{user_id_one: 1, user_id_two: 18},
	{user_id_one: 1, user_id_two: 19},
	{user_id_one: 1, user_id_two: 20},
	{user_id_one: 1, user_id_two: 21},
	{user_id_one: 1, user_id_two: 22},
	{user_id_one: 1, user_id_two: 23},
	{user_id_one: 1, user_id_two: 24},
	{user_id_one: 1, user_id_two: 25},
	{user_id_one: 1, user_id_two: 26},	
	{user_id_one: 1, user_id_two: 27},
	{user_id_one: 1, user_id_two: 28},
	{user_id_one: 1, user_id_two: 29},
	{user_id_one: 1, user_id_two: 30}
])